steps:
    # Step 1: Build the Docker image ---
  - name: 'gcr.io/cloud-builders/docker-2'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/my-docker-images/users-service:${_APP_VERSION}', '.']

    # Step 2: Push the Docker image
  - name: 'gcr.io/cloud-builders/docker-2'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/my-docker-images/users-service:${_APP_VERSION}']

    # Step 3: Deploy service to Kubernetes ---
  - name: 'gcr.io/cloud-builders/kubectl-2'
    id: 'deploy-service'
    args:
      - 'apply'
      - '-f'
      - 'cicd/users-service-service.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-central2'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-udemy-cluster'

    # Step 4: Deploy deployment to Kubernetes ---
  - name: 'gcr.io/cloud-builders/kubectl-2'
    id: 'deploy-deployment'
    args:
      - 'apply'
      - '-f'
      - 'cicd/users-service-deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-central2'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-udemy-cluster'

substitutions:
  _REGION: europe-central2 # Replace with your chosen region for Artifact Registry
  _APP_VERSION: '1.0.0' # Or 'v1.0.0', or 'develop-$(date +%Y%m%d%H%M%S)'
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/my-docker-images/users-service:${_APP_VERSION}'

options: # Add this section
  logging: CLOUD_LOGGING_ONLY